<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Blog.aspx.cs" Inherits="HopeForHumanity.Blog" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <script src="assets/js/gtag.js"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="keywords" content="African Children, Orphans, Donate, Donation, Charity, Shelter, Rehabilitation" />
    <!--Search engine optimization-->
    <meta name="description" content="Hope for humanity is a foundation that provides help to people in need, feeding and nurturing african children, orphans. Charity website. Donate to african children. Free slaves Libya" />
    <meta name="robots" content="index,follow" />
    <meta name="DC.title" content="Hope For Humanity Charity Website" />
    <title>Blog - Hope For Humanity</title>
    <link rel="shortcut icon" type="image/x-icon" href="favico.ico" />
    <!-- google fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lato:400,300italic,300,700%7CPlayfair+Display:400,700italic%7CRoboto:300%7CMontserrat:400,700%7COpen+Sans:400,300%7CLibre+Baskerville:400,400italic' rel='stylesheet' type='text/css' />
    <!-- Bootstrap -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="assets/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="assets/revolution-slider/css/settings.css" rel="stylesheet" />
    <link href="assets/css/global.css" rel="stylesheet" />
    <link href="assets/css/style.css" rel="stylesheet" />
    <link href="assets/css/responsive.css" rel="stylesheet" />
    <link href="assets/css/skin.css" rel="stylesheet" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
    <form id="form1" runat="server">
        <div id="wrapper">
            <!--Header Section Start Here -->
            <header id="header">
                <div class="container">
                    <div class="row primary-header">
                        <a href="Default.aspx" class="col-xs-12 col-sm-2 brand" title="Welcome to Hope For Humanity">
                            <img src="assets/img/logo.png" alt="Hope For Humanity" /></a>
                        <div class="social-links col-xs-12 col-sm-10">
                            <a href="Volunteer.aspx" class="btn btn-default btn-volunteer">Become volunteer</a>
                            <div runat="server" id="divLinks">
                                <!--Loaded from codebehind-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <!--MainMenu -->
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div id="divMainMenu" runat="server">
                            <!-- This part is autogenerated from backend code FillItems() -->
                        </div>
                        <!-- /.navbar-collapse -->
                        <!--MainMenu-->
                    </div>
                    <!-- /.container-fluid -->
                </div>

            </header>
            <!-- Header Section End Here -->

            <!-- site content -->
            <div id="main">
                <!--Breadcrumb Section Start Here-->
                <div class="breadcrumb-section">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <h1>Our Blog</h1>
                                <ul class="breadcrumb">
                                    <li>
                                        <a href="Default.aspx">Home</a>
                                    </li>
                                    <li class="active">Blog
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!--Breadcrumb Section End Here-->
                <div class="content-wrapper container" id="page-info">
                    <div class="row">
                        <!--Article Section Start Here-->
                        <div class="col-xs-12">
                            <!--block Frist Start Here-->
                            <article class="blog">
                                <figure>
                                    <img src="assets/img/blog-pic.jpg" alt="" />
                                </figure>
                                <div class="row">
                                    <div class="col-xs-12 col-sm-10 col-sm-offset-1 caption">
                                        <h2 class="h1">Fundraising initiatives for better life of the underprivileged children in Africa </h2>
                                        <ul class="post-in">
                                            <li>Posted In : Fundraising
                                            </li>
                                            <li>3 : comments
                                            </li>
                                        </ul>
                                        <p>
                                            Early December, 2017, fund raising initiatives were taken up and drives were launched to attract donations for the education of the underprivileged children. Many people participated in the event donated their hearts out. We assure our sponsors and contributors that the money will surely bring a great difference in the lives of these children.
                                        </p>
                                        <p>
                                            <a href="BlogDetails.aspx?Request=101400" class="btn btn-default" role="button">READ MORE</a>
                                        </p>
                                    </div>
                                </div>
                            </article>
                            <!--block Frist End Here-->
                            <!--block Second Start Here-->
                            <article class="blog anim-section">
                                <section class="img-slider flex-slide flexslider">
                                    <ul class="slides">
                                        <li>
                                            <img src="assets/img/blog-pic0.jpg" alt="" />
                                        </li>
                                        <li>
                                            <img src="assets/img/blog-pic1.jpg" alt="" />
                                        </li>
                                        <li>
                                            <img src="assets/img/blog-pic3.jpg" alt="" />
                                        </li>
                                    </ul>
                                </section>
                                <div class="row">
                                    <div class="col-xs-12 col-sm-10 col-sm-offset-1 caption">
                                        <h2 class="h1">Fundraising for African unprivileged children </h2>
                                        <ul class="post-in">
                                            <li>Posted In : Fundraising
                                            </li>
                                            <li>3 : comments
                                            </li>
                                        </ul>
                                        <p>
                                            We have been raising funds with great difficulty for the work that this charity does in Africa. We have just established a home for ophaned children in Eastern Malawi and also provided funding for widows to build businesses in order for them to help themselves and stimulate the local economy.
                                        </p>
                                        <p>
                                            We work with young women to train and develop their expertise in sewing and tailoring so they can start their own business and contribute to the community. This ensures that they avoid joining the cohort of ladies in the oldest industry known to man- the “night trade”.									
                                        </p>
                                        <p>
                                            <a href="BlogDetails.aspx?Request=101401" class="btn btn-default" role="button">READ MORE</a>
                                        </p>
                                    </div>
                                </div>
                            </article>
                            <!--block Second End Here-->
                            <!--block Third Start Here-->
                            <article class="blog anim-section">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <%--<img src="assets/img/video-frame3.jpg" alt="Click to play" data-video="http://www.youtube.com/embed/wN3gueLT0D8?autoplay=1" />--%>
                                    <iframe src="https://www.youtube.com/embed/OwoS1bmX7NI?autoplay=0" allowfullscreen></iframe>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12 col-sm-10 col-sm-offset-1 caption">
                                        <h2 class="h1">Bringing Changes in 2018 </h2>
                                        <ul class="post-in">
                                            <li>Posted In : Upcoming
                                            </li>
                                            <li>3 : comments
                                            </li>
                                        </ul>
                                        <p>
                                            The year 2017 has been a very exciting year for us and 2018 is promising to be even bigger. We are taking steps in preparation for 2018 to expand our influence throughout the rest of the Continent of Africa.	This is why your donation to this cause is so important to us and we treasure every single coin that goes towards our projects.
                                        </p>
                                        <p>
                                            <a href="BlogDetails.aspx?Request=101402" class="btn btn-default" role="button">READ MORE</a>
                                        </p>
                                    </div>
                                </div>
                            </article>
                            <!--block Third End Here-->
                            <!--block Fourth Start Here-->
                            <article class="blog anim-section">
                                <div class="row">
                                    <div class="col-xs-12 col-sm-10 col-sm-offset-1 caption">
                                        <ul class="post-in">
                                            <li>Posted In : Quotes
                                            </li>
                                            <li>10 : comments
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <blockquote class="blog-callout">
                                    <p>
                                        “We're really careful about amplifying the great work of others in every way that we can, and we don't like attaching our names to things.”								
                                    </p>
                                    <footer>
                                        Steve Jobs								
                                    </footer>
                                </blockquote>
                            </article>
                            <!--block Four End Here-->
                            <!--block Five Start Here-->
                            <section class="blog anim-section">
                                <div class="blog-alert">
                                    <h2 class="h1">We thank you for all your gifts and donations. Hope for Humanity family wishes you a merry new year.</h2>
                                    <a href="Default.aspx" class="embed-link"><i class="icon-embed"></i></a>
                                </div>
                            </section>
                            <!--block Five EHere-->
                            <!--block Six Start Here-->
                            <article class="blog anim-section">
                                <figure>
                                    <img src="assets/img/blog-pic2.jpg" alt="" />
                                </figure>
                                <div class="row">
                                    <div class="col-xs-12 col-sm-10 col-sm-offset-1 caption">
                                        <h2 class="h1">Improve the Health of some 200 kids in Uganda </h2>
                                        <ul class="post-in">
                                            <li>Posted In : Health
                                            </li>
                                            <li>5 : comments
                                            </li>
                                        </ul>
                                        <p>
                                            This project will purchase a motor bike to be used by a project health contact person to enable him monitor children's health in local villages. Visits by healthcare professionals to remote villages improve children's health by monitoring and increasing overall community awareness.									
                                        </p>
                                        <p>
                                            <a role="button" class="btn btn-default" href="BlogDetails.aspx?Request=101403">READ MORE</a>
                                        </p>
                                    </div>
                                </div>
                            </article>
                            <!--block Six End Here-->
                        </div>
                        <!--Article Section End Here-->
                    </div>
                </div>
            </div>
            <!-- site content ends -->

            <!--Footer Section End Here -->
            <footer id="footer">
                <div class="container" runat="server" id="divFooter">
                    <!--Generated From codebehind-->
                </div>
                <div class="copyright">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <span>&copy; Copyright
                                    <script>document.write(new Date().getFullYear())</script>
                                    , All Rights Reserved by Hope For Humanity Foundation.
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <!--Footer Section End Here -->
        </div>
        <script src="assets/js/jquery.min.js"></script>
        <!-- Switcher Style Js -->
        <script src="assets/js/style-switcher/assets/js/style.switcher.js"></script>
        <script src="assets/js/jquery.cookie.js"></script>
        <!-- Bootstrap Js-->
        <script src="assets/js/bootstrap.min.js"></script>
        <script src="assets/js/jquery.easing.min.js"></script>
        <!--Main Slider Js-->
        <script src="assets/revolution-slider/js/jquery.themepunch.plugins.min.js"></script>
        <script src="assets/revolution-slider/js/jquery.themepunch.revolution.js"></script>
        <!--Main Slider Js End -->
        <script src="assets/js/jquery.flexslider.js"></script>
        <script src="assets/js/site.js"></script>
        <!--Custom Js validation & stuff-->
        <script src="assets/js/custom.js"></script>
        <script>
            // functions autocomplete
            var people = ['<a href="CauseDetails.aspx?Request=101200">Shelter</a><br/>',
                '<a href="CauseDetails.aspx?Request=101201">Educate Girls</a><br/>',
                '<a href="CauseDetails.aspx?Request=101202">Grow Food</a><br/>',
                '<a href="CauseDetails.aspx?Request=101203">Feed a child</a><br/>',
                '<a href="CauseDetails.aspx?Request=101204">Build Schools</a><br/>',
                '<a href="CauseDetails.aspx?Request=101205">Health Care</a><br/>',
                '<a href="Volunteer.aspx">Volunteer</a><br/>',
                '<a href="Ourstory.aspx">Our Story</a><br/>',
                '<a href="Ourmission.aspx">Our Story</a><br/>',
                '<a href="Ourstory.aspx">Our Mission</a><br/>',
                '<a href="Events.aspx">Events</a><br/>',
                '<a href="Blog.aspx">Blog</a><br/>'];

            function matchPeople(input) {
                var reg = new RegExp(input.split('').join('\\w*\\s*\\w*').replace(/\W/, ""), 'i');
                return people.filter(function (person) {
                    if (person.match(reg)) {
                        return person;
                    }
                });
            }

            function changeInput(val) {
                var test = '';
                var autoCompleteResult = matchPeople(val);
                if (val != '') {
                    for (i = 0; i < autoCompleteResult.length; i++) {
                        test += autoCompleteResult[i];
                    }
                    document.getElementById("result").innerHTML = test;
                }
                else
                    document.getElementById("result").innerHTML = '';
            }
        </script>
    </form>
</body>
</html>
