<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Causes.aspx.cs" Inherits="HopeForHumanity.Causes" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <script src="assets/js/gtag.js"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="keywords" content="African Children, Orphans, Donate, Donation, Charity, Shelter, Rehabilitation" />
    <!--Search engine optimization-->
    <meta name="description" content="Hope for humanity is a foundation that provides help to people in need, feeding and nurturing african children, orphans. Charity website. Donate to african children. Free slaves Libya" />
    <meta name="robots" content="index,follow" />
    <meta name="DC.title" content="Hope For Humanity Charity Website" />
    <title>Causes - Hope For Humanity</title>
    <link rel="shortcut icon" type="image/x-icon" href="favico.ico" />
    <!-- google fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lato:400,300italic,300,700%7CPlayfair+Display:400,700italic%7CRoboto:300%7CMontserrat:400,700%7COpen+Sans:400,300%7CLibre+Baskerville:400,400italic' rel='stylesheet' type='text/css' />
    <!-- Bootstrap -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="assets/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="assets/revolution-slider/css/settings.css" rel="stylesheet" />
    <link href="assets/css/global.css" rel="stylesheet" />
    <link href="assets/css/style.css" rel="stylesheet" />
    <link href="assets/css/responsive.css" rel="stylesheet" />
    <link href="assets/css/skin.css" rel="stylesheet" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
    <form id="form1" runat="server">
        <div id="wrapper">
            <!--Header Section Start Here -->
            <header id="header">
                <div class="container">
                    <div class="row primary-header">
                        <a href="Default.aspx" class="col-xs-12 col-sm-2 brand" title="Welcome to Hope For Humanity">
                            <img src="assets/img/logo.png" alt="Hope For Humanity" /></a>
                        <div class="social-links col-xs-12 col-sm-10">
                            <a href="Volunteer.aspx" class="btn btn-default btn-volunteer">Become volunteer</a>
                            <div runat="server" id="divLinks">
                                <!--Loaded from codebehind-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <!--MainMenu -->
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div id="divMainMenu" runat="server">
                            <!-- This part is autogenerated from backend code FillItems() -->
                        </div>
                        <!-- /.navbar-collapse -->
                        <!--MainMenu-->
                    </div>
                    <!-- /.container-fluid -->
                </div>
            </header>
            <!-- Header Section End Here -->

            <!-- site content -->
            <div id="main">
                <!--Breadcrumb Section Start Here-->
                <div class="breadcrumb-section">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <h1>Causes</h1>
                                <ul class="breadcrumb">
                                    <li>
                                        <a href="Default.aspx">Home</a>
                                    </li>
                                    <li class="active">Causes
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!--Breadcrumb Section End Here-->
                <!-- cause page Start Here-->
                <div class="content-wrapper cause-page-section" id="page-info">
                    <div class="container">
                        <section class="our-story row anim-section">
                            <div class="col-xs-12">
                                <header class="page-header section-header top-spacer">
                                    <h2>A little goes a long way in helping a child somewhere. <strong>Our causes</strong></h2>
                                </header>

                                <!-- breadcrumb section -->
                                <div class="sec-breadcrumb text-center">
                                    <span><strong>Check out our causes below.</strong></span>
                                </div>
                                <!-- breadcrumb section -->

                            </div>
                        </section>

                        <!-- Our Causes Section-->
                        <section class="our-causes">
                            <div class="anim-section">
                                <div class="row">

                                    <!-- Article Section Srart Here -->
                                    <div class="article-list progressbar">
                                        <div class="cols-xs-12 col-sm-4 anim-section">
                                            <div class="spacer-bottom zoom equal-box">
                                                <h3 class="h5">Help African children to get shelter</h3>
                                                <a href="CauseDetails.aspx?Request=101200" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-01.jpg" alt="" width="600" height="400" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="9.7" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">9.7% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$58,354 <small>/ $600,000</small></span></span>
                                                <p>
                                                    With your donation, orphaned african children get to live in better housing environments and childrens homes.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </div>
                                        <div class="cols-xs-12 col-sm-4 anim-section">
                                            <div class="spacer-bottom zoom equal-box">
                                                <h3 class="h5">Help girls to get Education</h3>
                                                <a href="CauseDetails.aspx?Request=101201" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-02.jpg" alt="" width="600" height="400" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="7.7" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">7.7% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$93,106 <small>/ $1,206,540</small></span></span>
                                                <p>
                                                    Give an opportunity to girls to become educated, so that, they can stand with boys and get a self exposure worldwide.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </div>
                                        <div class="cols-xs-12 col-sm-4 anim-section">
                                            <div class="spacer-bottom zoom equal-box">
                                                <h3 class="h5">Help us grow food for the children</h3>
                                                <a href="CauseDetails.aspx?Request=101202" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-03.jpg" alt="" width="600" height="400" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="18.8" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">18.8% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$150,620 <small>/ $800,000</small></span></span>
                                                <p>
                                                    You can offer your support today and help us in the farm. We grow and rare farm animals to feed the children.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </div>
                                        <div class="cols-xs-12 col-sm-4 anim-section">
                                            <div class="spacer-bottom zoom equal-box">
                                                <h3 class="h5">Feed a child Program</h3>
                                                <a href="CauseDetails.aspx?Request=101203" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-04.jpg" alt="" width="600" height="400" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="18.2" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">18.2% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$456,200 <small>/ $2,500,00</small></span></span>
                                                <p>
                                                    We support over 60 children's home establishments across Africa in feeding children. We need your help in this gigantic task.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </div>
                                        <div class="cols-xs-12 col-sm-4 anim-section">
                                            <div class="spacer-bottom zoom equal-box">
                                                <h3 class="h5">Help us build schools</h3>
                                                <a href="CauseDetails.aspx?Request=101204" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-05.jpg" alt="" width="600" height="400" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="25.01" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">25.01% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$750,305 <small>/ $3,000,000</small></span></span>
                                                <p>
                                                    School infrastructure is a major issue in most parts of africa and we need your help to build more schools.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </div>
                                        <div class="cols-xs-12 col-sm-4 anim-section">
                                            <div class="spacer-bottom zoom equal-box">
                                                <h3 class="h5">Give a child basic medical care</h3>
                                                <a href="CauseDetails.aspx?Request=101205" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-06.jpg" alt="" width="600" height="400" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">80% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$850,000 <small>/ $1,300,000</small></span></span>
                                                <p>
                                                    With your support, children are able to get access to basic medical care through our medical care program.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Article Section Srart Here -->

                                </div>
                            </div>
                        </section>
                        <!-- Our Causes Section End-->
                    </div>

                </div>
                <!-- cause page Start End-->
            </div>
            <!-- site content ends -->

            <!--Footer Section Start Here -->
            <footer id="footer">
                <div class="container" runat="server" id="divFooter">
                    <!--Generated From codebehind-->
                </div>
                <div class="copyright">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <span>&copy; Copyright
                                    <script>document.write(new Date().getFullYear())</script>
                                    , All Rights Reserved by Hope For Humanity Foundation.
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <!--Footer Section End Here -->
        </div>

        <!-- donation form popup -->
        <div class="modal donate-form">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                        <header class="page-header">
                            <h2>You are donating to. <strong>Hope For Humanity</strong></h2>
                        </header>
                    </div>
                    <div class="modal-body">
                        <div role="form">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label>How much would you like to donate ?<br /> (NB: We accept bitcoin.)</label>
                                        <div class="choose-pricing">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default active" onclick="mySetDonation('25')">
                                                    $25
                                                </button>
                                                <button type="button" class="btn btn-default" onclick="mySetDonation('50')">
                                                    $50
                                                </button>
                                                <button type="button" class="btn btn-default" onclick="mySetDonation('100')">
                                                    $100
                                                </button>
                                                <input type="text" placeholder="Custom" class="inpt-first form-control" runat="server" id="iAmount" />
                                                <asp:HiddenField runat="server" ID="hfAmount" Value="25" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row display">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <div class="dropdown">
                                            <asp:DropDownList ID="ddlType" runat="server" class="btn btn-width dropdown-toggle">
                                                <asp:ListItem Text="Donation Type" Value="Type"></asp:ListItem>
                                                <asp:ListItem Text="Educate A Child" Value="Educate"></asp:ListItem>
                                                <asp:ListItem Text="Feed A Child" Value="Feed"></asp:ListItem>
                                                <asp:ListItem Text="Grow Food" Value="Grow"></asp:ListItem>
                                                <asp:ListItem Text="Build Schools" Value="School"></asp:ListItem>
                                                <asp:ListItem Text="Health Care" Value="Health"></asp:ListItem>
                                            </asp:DropDownList>
                                            <label id="ddlType-error" style="color: red; display: none;">*</label>
                                        </div>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <div class="dropdown">
                                            <asp:DropDownList ID="ddlFreq" runat="server" class="btn btn-width dropdown-toggle">
                                                <asp:ListItem Text="One Time Donation" Value="Once" Selected></asp:ListItem>
                                                <asp:ListItem Text="Every Month (Recurring)" Value="Monthly"></asp:ListItem>
                                            </asp:DropDownList>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="name">First Name<span>*</span></label>
                                        <input type="text" class="form-control" id="fname" runat="server" />
                                        <label id="fname-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="last-name">Last Name<span>*</span></label>
                                        <input type="text" class="form-control" id="lname" runat="server" />
                                        <label id="lname-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="name">Email<span>*</span></label>
                                        <input type="text" class="form-control" id="email" runat="server" />
                                        <label id="email-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="phone">Phone<span>*</span></label>
                                        <input type="text" class="form-control" id="phone" runat="server" />
                                        <label id="phone-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="message">Address<span>*</span></label>
                                        <textarea class="form-control" id="Address" runat="server"></textarea>
                                        <label id="Address-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="add-note">Additional Note</label>
                                        <textarea class="form-control" id="message" runat="server"></textarea>
                                        <label id="message-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12">
                                        <asp:Button runat="server" ID="btnDonateBitcoin" Text="DONATE WITH BITCOIN" class="btn btn-default pull-left" OnClientClick="return validateForm()" OnClick="btnDonateBitcoin_Click" />
                                        <asp:Button runat="server" ID="btnDonate" Text="DONATE" class="btn btn-default pull-right" OnClientClick="return validateForm()" OnClick="btnDonate_Click" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12">
                                        <p class="forms-notes">
                                            Note: The Hope For Humanity Foundation is a US tax-exempt 501(c)(3) non-profit organization. Your gift is tax-deductible as allowed by law.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- donation form popup -->


        <script src="assets/js/jquery.min.js"></script>
        <!-- Switcher Style Js -->
        <script src="assets/js/style-switcher/assets/js/style.switcher.js"></script>
        <script src="assets/js/jquery.cookie.js"></script>
        <!-- Bootstrap Js-->
        <script src="assets/js/bootstrap.min.js"></script>
        <script src="assets/js/jquery.easing.min.js"></script>
        <!--Main Slider Js-->
        <script src="assets/revolution-slider/js/jquery.themepunch.plugins.min.js"></script>
        <script src="assets/revolution-slider/js/jquery.themepunch.revolution.js"></script>
        <!--Main Slider Js End -->
        <script src="assets/js/jquery.flexslider.js"></script>
        <script src="assets/js/site.js"></script>
        <!--Custom Js validation & stuff-->
        <script src="assets/js/custom.js"></script>
        <script>
            // functions autocomplete
            var people = ['<a href="CauseDetails.aspx?Request=101200">Shelter</a><br/>',
                '<a href="CauseDetails.aspx?Request=101201">Educate Girls</a><br/>',
                '<a href="CauseDetails.aspx?Request=101202">Grow Food</a><br/>',
                '<a href="CauseDetails.aspx?Request=101203">Feed a child</a><br/>',
                '<a href="CauseDetails.aspx?Request=101204">Build Schools</a><br/>',
                '<a href="CauseDetails.aspx?Request=101205">Health Care</a><br/>',
                '<a href="Volunteer.aspx">Volunteer</a><br/>',
                '<a href="Ourstory.aspx">Our Story</a><br/>',
                '<a href="Ourmission.aspx">Our Story</a><br/>',
                '<a href="Ourstory.aspx">Our Mission</a><br/>',
                '<a href="Events.aspx">Events</a><br/>',
                '<a href="Blog.aspx">Blog</a><br/>'];

            function matchPeople(input) {
                var reg = new RegExp(input.split('').join('\\w*\\s*\\w*').replace(/\W/, ""), 'i');
                return people.filter(function (person) {
                    if (person.match(reg)) {
                        return person;
                    }
                });
            }

            function changeInput(val) {
                var test = '';
                var autoCompleteResult = matchPeople(val);
                if (val != '') {
                    for (i = 0; i < autoCompleteResult.length; i++) {
                        test += autoCompleteResult[i];
                    }
                    document.getElementById("result").innerHTML = test;
                }
                else
                    document.getElementById("result").innerHTML = '';
            }
        </script>
    </form>
</body>
</html>
