<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="HopeForHumanity.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <script src="assets/js/gtag.js"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="keywords" content="African Children, Orphans, Donate, Donation, Charity, Shelter, Rehabilitation" />
    <!--Search engine optimization-->
    <meta name="description" content="Hope for humanity is a foundation that provides help to people in need, feeding and nurturing african children, orphans. Charity website. Donate to african children. Free slaves Libya" />
    <meta name="robots" content="index,follow" />
    <meta name="DC.title" content="Hope For Humanity Charity Website" />
    <title>Home - Hope For Humanity</title>
    <link rel="shortcut icon" type="image/x-icon" href="favico.ico" />
    <!-- google fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lato:400,300italic,300,700%7CPlayfair+Display:400,700italic%7CRoboto:300%7CMontserrat:400,700%7COpen+Sans:400,300%7CLibre+Baskerville:400,400italic' rel='stylesheet' type='text/css' />
    <!-- Bootstrap -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="assets/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="assets/revolution-slider/css/settings.css" rel="stylesheet" />
    <link href="assets/css/global.css" rel="stylesheet" />
    <link href="assets/css/style.css" rel="stylesheet" />
    <link href="assets/css/responsive.css" rel="stylesheet" />
    <link href="assets/css/skin.css" rel="stylesheet" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
    <form id="form1" runat="server">
        <div id="wrapper">
            <!--Header Section Start Here -->
            <header id="header">
                <div class="container">
                    <div class="row primary-header">
                        <a href="Default.aspx" class="col-xs-12 col-sm-2 brand" title="Welcome to Hope For Humanity">
                            <img src="assets/img/logo.png" alt="Hope For Humanity" /></a>
                        <div class="social-links col-xs-12 col-sm-10">
                            <a href="Volunteer.aspx" class="btn btn-default btn-volunteer">Become volunteer</a>
                            <div runat="server" id="divLinks">
                                <!--Loaded from codebehind-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <!--MainMenu -->
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div id="divMainMenu" runat="server">
                            <!-- This part is autogenerated from backend code FillItems() -->
                        </div>
                        <!-- /.navbar-collapse -->
                        <!--MainMenu-->
                    </div>
                    <!-- /.container-fluid -->
                </div>

            </header>
            <!-- Header Section End Here -->

            <!-- Site Content -->
            <div id="main">
                <!-- banner slider Start Here -->
                <section class="rev_slider_wrapper banner-section">
                    <div class="rev_slider banner-slider">
                        <ul>
                            <!-- SLIDE  -->
                            <li data-transition="random" data-slotamount="7" data-masterspeed="500" class="slide-1">
                                <!-- MAIN IMAGE -->
                                <img src="assets/img/slide-banner-01.jpg" alt="banner" data-bgfit="cover" data-bgposition="center 36%" data-bgrepeat="no-repeat" />
                                <div
                                    data-endspeed="500"
                                    data-easing="easeOutCirc"
                                    data-start="500"
                                    data-speed="700"
                                    data-y="103"
                                    data-x="152"
                                    class="tp-caption sft">
                                    <a href="CauseDetails.aspx?Request=101200"><span class="btn btn-bg">FEATURED CAUSE</span></a>
                                </div>
                                <div
                                    data-endspeed="800"
                                    data-easing="easeOutCirc"
                                    data-start="800"
                                    data-speed="700"
                                    data-y="150"
                                    data-x="152"
                                    class="tp-caption sft banner-heading">
                                    <h2 style="color: white;"><strong>Donate &amp; Help</strong>
                                        Raise Funds For African Children in need
                                    </h2>
                                </div>
                                <div
                                    data-endspeed="1000"
                                    data-easing="easeOutCirc"
                                    data-start="1000"
                                    data-speed="700"
                                    data-y="304"
                                    data-x="152"
                                    class="tp-caption sft banner-summary">
                                    <p style="color: white;">
                                        <strong>You can offer your help to African children by raising money for ideal causes including medical bills, education among other donation causes.
                                        </strong>
                                    </p>
                                </div>
                                <div
                                    data-endspeed="1200"
                                    data-easing="easeOutCirc"
                                    data-start="1200"
                                    data-speed="700"
                                    data-y="416"
                                    data-x="152"
                                    class="tp-caption sft">
                                    <a style="color: white;" data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">Donate NOW</a>
                                </div>
                            </li>
                            <!-- SLIDE  -->
                            <!-- SLIDE  -->
                            <li data-transition="random" data-slotamount="7" data-masterspeed="500" class="slide-2">
                                <!-- MAIN IMAGE -->
                                <img src="assets/img/slide-banner-02.jpg" alt="banner" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" />
                                <div
                                    data-endspeed="500"
                                    data-easing="easeOutCirc"
                                    data-start="500"
                                    data-speed="500"
                                    data-y="406"
                                    data-x="152"
                                    class="tp-caption sfb feature-btn ">
                                    <a href="CauseDetails.aspx?Request=101202"><span class="btn btn-warning btn-sm">FEATURED CAUSE</span></a>
                                </div>
                                <div
                                    data-endspeed="800"
                                    data-easing="easeOutCirc"
                                    data-start="800"
                                    data-speed="500"
                                    data-y="448"
                                    data-x="152"
                                    class="tp-caption sfb">
                                    <div class="trans-grey"></div>
                                </div>
                                <div
                                    data-endspeed="1500"
                                    data-easing="easeOutCirc"
                                    data-start="1500"
                                    data-speed="1000"
                                    data-y="466"
                                    data-x="177"
                                    class="tp-caption banner-heading bottom-animation text-white sfb">
                                    <h2 class="h1"><strong>Donate &amp; Help</strong>
                                        Feed a child program</h2>
                                </div>
                                <div
                                    data-endspeed="1700"
                                    data-easing="easeOutCirc"
                                    data-start="1700"
                                    data-speed="700"
                                    data-y="550"
                                    data-x="177"
                                    class="tp-caption sfb donate-button">
                                    <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn-link">Donate NOW</a>
                                </div>
                            </li>
                            <!-- SLIDE  -->
                            <li data-transition="random" data-slotamount="7" data-masterspeed="500" class="slide-3">
                                <!-- MAIN IMAGE -->
                                <img src="assets/img/slide-banner-03.jpg" alt="banner" data-bgfit="cover" data-bgposition="center 36%" data-bgrepeat="no-repeat" />
                                <div
                                    data-endspeed="500"
                                    data-easing="easeOutCirc"
                                    data-start="500"
                                    data-speed="700"
                                    data-y="103"
                                    data-x="152"
                                    class="tp-caption sft banner-feaure">
                                    <a href="CauseDetails.aspx?Request=101201"><span class="btn btn-bg">FEATURED CAUSE</span></a>
                                </div>
                                <div
                                    data-endspeed="800"
                                    data-easing="easeOutCirc"
                                    data-start="800"
                                    data-speed="700"
                                    data-y="150"
                                    data-x="152"
                                    class="tp-caption sft third-style banner-heading banner-title">
                                    <h2><strong>Donate &amp; Help</strong>
                                        Support African Orphans Make Their Career</h2>
                                </div>
                                <div
                                    data-endspeed="1000"
                                    data-easing="easeOutCirc"
                                    data-start="1000"
                                    data-speed="700"
                                    data-y="244"
                                    data-x="152"
                                    class="tp-caption sft third-style banner-summary banner-description">
                                    <p>
                                        Start donating for the african child who is unable to get the necessary education in life. Give your full support to make their career a dream come true.
                                    </p>
                                </div>
                                <div
                                    data-endspeed="1200"
                                    data-easing="easeOutCirc"
                                    data-start="1200"
                                    data-speed="700"
                                    data-y="354"
                                    data-x="152"
                                    class="tp-caption sft banner-btn">
                                    <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">Donate NOW</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </section>
                <!-- banner slider End Here -->

                <!-- Our Causes Section Start Here-->
                <section class="our-causes">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="page-header section-header clearfix">
                                    <h2>Help multifarious people with your gift or donation. <strong>See Our Causes Below</strong></h2>
                                </div>

                                <div class="article-list flexslider article-slider progressbar">
                                    <ul class="slides">
                                        <li>
                                            <div class="items zoom">
                                                <h3 class="h6">Help African Children Get Their Own Homes</h3>
                                                <a href="CauseDetails.aspx?Request=101200" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-01.jpg" alt="" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="9.7" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">9.7% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$58,354 <small>/ $600,000</small></span></span>
                                                <p>
                                                    With your donation, orphaned african children get to live in better housing environments and childrens homes.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="items zoom">
                                                <h3 class="h6">Make Girls Educated To Aid Them Earn Reputable Positions</h3>
                                                <a href="CauseDetails.aspx?Request=101201" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-02.jpg" alt="" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="7.7" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">7.7% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$93,106 <small>/ $1,206,540</small></span></span>
                                                <p>
                                                    Give an opportunity to girls to become educated, so that, they can stand with boys and get a self exposure worldwide.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="items zoom">
                                                <h3 class="h6">Help us grow food for the children</h3>
                                                <a href="CauseDetails.aspx?Request=101202" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-03.jpg" alt="" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="18.8" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">18.8% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$150,620 <small>/ $800,000</small></span></span>
                                                <p>
                                                    You can offer your support today and help us in the farm. We grow and rare farm animals to feed the children.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="items zoom">
                                                <h3 class="h6">Feed a child Program</h3>
                                                <a href="CauseDetails.aspx?Request=101203" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-04.jpg" alt="" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="18.2" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">18.2% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$456,200 <small>/ $2,500,00</small></span></span>
                                                <p>
                                                    We support over 60 children's home establishments across Africa in feeding children. We need your help in this gigantic task.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="items zoom">
                                                <h3 class="h6">We are building schools</h3>
                                                <a href="CauseDetails.aspx?Request=101204" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-05.jpg" alt="" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="25.01" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">25.01% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$750,305 <small>/ $3,000,000</small></span></span>
                                                <p>
                                                    School infrastructure is a major issue in most parts of africa and we need your help to build more schools.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="items zoom">
                                                <h3 class="h6">Give a child basic medical care</h3>
                                                <a href="CauseDetails.aspx?Request=101205" class="img-thumb">
                                                    <figure>
                                                        <img src="assets/img/img-slide-06.jpg" alt="" />
                                                    </figure>
                                                </a>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="progress-value">80% </span>
                                                    </div>
                                                </div>
                                                <span class="donation">Progress/Target : <span class="value">$850,000 <small>/ $1,300,000</small></span></span>
                                                <p>
                                                    With your support, children are able to get access to basic medical care through our medical care program.
                                                </p>
                                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-default">DONATE NOW</a>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Our Causes Section End Here-->

                <!-- How To Help Section Start Here -->
                <section class="how-to-help">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 ">
                                <header class="page-header section-header">
                                    <h2>How you can help? <strong>See below</strong></h2>
                                </header>
                                <div class="row help-list">
                                    <div class="col-xs-12 col-sm-6 col-lg-5">
                                        <article class="media">
                                            <a class="pull-left warning-icon-box" href="Ourstory.aspx"><i class="icon-volume"></i></a>
                                            <div class="media-body less-width">
                                                <h3 class="media-heading">Media</h3>
                                                <p>
                                                    Donate money anywhere &amp; at anytime to offer help to African children through different medium.
                                                </p>
                                            </div>
                                        </article>
                                        <article class="media">
                                            <a class="pull-left warning-icon-box" href="Volunteer.aspx"><i class="icon-user"></i></a>
                                            <div class="media-body less-width">
                                                <h3 class="media-heading">Become Volunteer</h3>
                                                <p>
                                                    Take initiate to become a volunteer and help those people, who do not have any hope for good living.

                                                </p>
                                            </div>
                                        </article>
                                        <article class="media">
                                            <a class="pull-left warning-icon-box" href="~/Error404.aspx" data-toggle="modal" data-target=".donate-form"><i class="icon-heart"></i></a>
                                            <div class="media-body less-width">
                                                <h3 class="media-heading">Send Donation</h3>
                                                <p>
                                                    Choose any medium either offline or online to send donation and aid NGOs like ours to support people who are facing poverty.
                                                </p>
                                            </div>
                                        </article>
                                    </div>
                                    <div class="col-xs-12 col-sm-6 col-lg-6 col-lg-offset-1">
                                        <div class="embed-responsive embed-responsive-16by9">
                                            <%--<img src="assets/img/video-frame.jpg" alt="Click to play" data-video="https://www.youtube.com/embed/QBY7DKE0vI4?autoplay=1" />--%>
                                            <iframe src="https://www.youtube.com/embed/QBY7DKE0vI4?autoplay=0" allowfullscreen></iframe>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
                <!-- How To Help Section End Here-->

                <!-- Become Volunteer Section Start Here -->
                <section class="parallax-section parallax">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 col-sm-7 col-md-5">
                                <h2>Become <strong>Volunteer</strong></h2>
                                <p style="color: black;">
                                    <strong>Spread the awareness of helping people, so that they can live a normal life in the society and get the education that everyone deserves.
                                    </strong>
                                </p>
                                <a data-toggle="modal" href="~/Error404.aspx" data-target=".join-now-form" class="btn btn-default">Join Now</a>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Become Volunteer Section End Here -->

                <!-- Latest News Section Start Here -->
                <section class="latest-news ">
                    <div class="container anim-section">
                        <div class="row">
                            <div class="col-xs-12">
                                <header class="page-header section-header clearfix">
                                    <h2>Checkout whats going on. <strong>Latest News</strong></h2>
                                </header>

                                <div class="article-list row">
                                    <div class="items zoom col-xs-12 col-sm-4">
                                        <a href="BlogDetails.aspx?Request=101400" class="img-thumb">
                                            <figure>
                                                <img src="assets/img/img-slide-04.jpg" alt="" />
                                            </figure>
                                        </a>
                                        <h3>Fund raising initiatives</h3>
                                        <span class="date">18 DEC 2017</span><span class="posted-in">Posted In : Fund Raising</span>
                                        <p>
                                            Early December, 2017, fund raising initiatives were taken up and drives were launched to attract donations for the education of the underprivileged children. Many people participated in the event donated their hearts out. We assure our sponsors and contributors that the money will surely bring a great difference in the lives of these children.
                                        </p>
                                        <a href="BlogDetails.aspx?Request=101400" class="btn btn-default">READ MORE</a>
                                    </div>
                                    <div class="items zoom col-xs-12 col-sm-4">
                                        <a href="BlogDetails.aspx?Request=101401" class="img-thumb">
                                            <figure>
                                                <img src="assets/img/img-slide-05.jpg" alt="" />
                                            </figure>
                                        </a>
                                        <h3>Fundraising for African unprivileged children</h3>
                                        <span class="date">09 DEC 2017</span><span class="posted-in">Posted In : Fund Raising</span>
                                        <p>
                                            We have been raising funds with great difficulty for the work that this charity does in Africa. We have just established a home for ophaned children in Eastern Malawi and also provided funding for widows to build businesses in order for them to help themselves and stimulate the local economy.
                                        </p>
                                        <a href="BlogDetails.aspx?Request=101401" class="btn btn-default">READ MORE</a>
                                    </div>
                                    <div class="items zoom col-xs-12 col-sm-4">
                                        <a href="BlogDetails.aspx?Request=101402" class="img-thumb">
                                            <figure>
                                                <img src="assets/img/img-slide-06.jpg" alt="" />
                                            </figure>
                                        </a>
                                        <h3>Bringing Change in 2018</h3>
                                        <span class="date">20 DEC 2017</span><span class="posted-in">Posted In : Upcoming</span>
                                        <p>
                                            The year 2017 has been a very exciting year for us and 2018 is promising to be even bigger. We are taking steps in preparation for 2018 to expand our influence throughout the rest of the Continent of Africa.	This is why your donation to this cause is so important to us and we treasure every single coin that goes towards our projects.
                                        </p>
                                        <a href="BlogDetails.aspx?Request=101402" class="btn btn-default">READ MORE</a>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Latest News Section End Here -->

                <!--Testimonial Section Start Here -->
                <section class="testimonial parallax">
                    <div class="overlay"></div>
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="testimonial-slider flexslider">
                                    <ul class="slides">
                                        <li>
                                            <div class="slide">
                                                <h2>Donation Holders say <strong>Read Below </strong></h2>
                                                <blockquote>
                                                    <p>
                                                        “No act of kindness no matter how small is ever a waste of time.”
                                                    </p>
                                                    <footer>
                                                        <span>Jonathan Ross</span>
                                                        <cite>(CEO Smirvec Labs)</cite>
                                                    </footer>
                                                </blockquote>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="slide">
                                                <h2>Donation Holders say <strong>Read Below</strong></h2>
                                                <blockquote>
                                                    <p>
                                                        “We make a living by what we get, but we make a life by what we give.”
                                                    </p>
                                                    <footer>
                                                        <span>Michael Shuttleworth</span>
                                                        <cite>(Head of Sales at Newman Group)</cite>
                                                    </footer>
                                                </blockquote>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="slide">
                                                <h2>Donation Holders say <strong>Read Below</strong></h2>
                                                <blockquote>
                                                    <p>
                                                        “Giving is not just about making a donation. Its about making a difference.”
                                                    </p>
                                                    <footer>
                                                        <span>Nathan Ribeiro</span>
                                                        <cite>(Managing director of Bodain Technology)</cite>
                                                    </footer>
                                                </blockquote>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!--Testimonial Section End Here -->

            </div>
            <!--Site Content End Here -->

            <!--Footer Section Start Here -->
            <footer id="footer">
                <div class="container" runat="server" id="divFooter">
                    <!--Generated From codebehind-->
                </div>
                <div class="copyright">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <span>&copy; Copyright
                                    <script>document.write(new Date().getFullYear())</script>
                                    , All Rights Reserved by Hope For Humanity Foundation.
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <!--Footer Section End Here -->
        </div>



        <!-- join now form popup -->
        <div class="modal join-now-form">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                        <header class="page-header">
                            <h2>Become a <strong>Volunteer</strong></h2>
                        </header>
                    </div>
                    <div class="modal-body">
                        <div role="form">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="name-join">Name<span>*</span></label>
                                        <input type="text" class="form-control" id="name-join" />
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="last-name-join">Last Name<span>*</span></label>
                                        <input type="text" class="form-control" id="last-name-join" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="email-join">Email<span>*</span></label>
                                        <input type="text" class="form-control" id="email-join" />
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="phone-join">Phone<span>*</span></label>
                                        <input type="text" class="form-control" id="phone-join" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="zip-code-join">ZIP code<span>*</span></label>
                                        <input type="password" class="form-control" id="zip-code-join" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12">
                                        <label for="message-join">Why you join volunteer<span>*</span></label>
                                        <textarea class="form-control" id="message-join"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12">
                                        <button type="button" class="btn btn-default pull-right">
                                            Submit
                                        </button>

                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12">
                                        <p class="forms-notes">
                                            Note: Thank you for offering us your help.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- join now form popup -->

        <!-- donation form popup -->
        <div class="modal donate-form">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                        <header class="page-header">
                            <h2>You are donating to. <strong>Hope For Humanity</strong></h2>
                        </header>
                    </div>
                    <div class="modal-body">
                        <div role="form">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label>How much would you like to donate ?<br /> (NB: We accept bitcoin.)</label>
                                        <div class="choose-pricing">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default active" onclick="mySetDonation('25')">
                                                    $25
                                                </button>
                                                <button type="button" class="btn btn-default" onclick="mySetDonation('50')">
                                                    $50
                                                </button>
                                                <button type="button" class="btn btn-default" onclick="mySetDonation('100')">
                                                    $100
                                                </button>
                                                <input type="text" placeholder="Custom" class="inpt-first form-control" runat="server" id="iAmount" />
                                                <asp:HiddenField runat="server" ID="hfAmount" Value="25" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row display">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <div class="dropdown">
                                            <asp:DropDownList ID="ddlType" runat="server" class="btn btn-width dropdown-toggle">
                                                <asp:ListItem Text="Donation Type" Value="Type"></asp:ListItem>
                                                <asp:ListItem Text="Educate A Child" Value="Educate"></asp:ListItem>
                                                <asp:ListItem Text="Feed A Child" Value="Feed"></asp:ListItem>
                                                <asp:ListItem Text="Grow Food" Value="Grow"></asp:ListItem>
                                                <asp:ListItem Text="Build Schools" Value="School"></asp:ListItem>
                                                <asp:ListItem Text="Health Care" Value="Health"></asp:ListItem>
                                            </asp:DropDownList>
                                            <label id="ddlType-error" style="color: red; display: none;">*</label>
                                        </div>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <div class="dropdown">
                                            <asp:DropDownList ID="ddlFreq" runat="server" class="btn btn-width dropdown-toggle">
                                                <asp:ListItem Text="One Time Donation" Value="Once" Selected></asp:ListItem>
                                                <asp:ListItem Text="Every Month (Recurring)" Value="Monthly"></asp:ListItem>
                                            </asp:DropDownList>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="name">First Name<span>*</span></label>
                                        <input type="text" class="form-control" id="fname" runat="server" />
                                        <label id="fname-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="last-name">Last Name<span>*</span></label>
                                        <input type="text" class="form-control" id="lname" runat="server" />
                                        <label id="lname-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="name">Email<span>*</span></label>
                                        <input type="text" class="form-control" id="email" runat="server" />
                                        <label id="email-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="phone">Phone<span>*</span></label>
                                        <input type="text" class="form-control" id="phone" runat="server" />
                                        <label id="phone-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="message">Address<span>*</span></label>
                                        <textarea class="form-control" id="Address" runat="server"></textarea>
                                        <label id="Address-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="add-note">Additional Note</label>
                                        <textarea class="form-control" id="message" runat="server"></textarea>
                                        <label id="message-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12">
                                        <asp:Button runat="server" ID="btnDonateBitcoin" Text="DONATE WITH BITCOIN" class="btn btn-default pull-left" OnClientClick="return validateForm()" OnClick="btnDonateBitcoin_Click" />
                                        <%--<asp:Button runat="server" ID="btnDonate" Text="DONATE" class="btn btn-default pull-right" OnClientClick="return validateForm()" OnClick="btnDonate_Click" />--%>
                                        <asp:ImageButton runat="server" ID="btnImageDonate" AlternateText="DONATE" class="btn btn-default pull-right" OnClientClick="return validateForm()" OnClick="btnDonate_Click" ImageUrl="~/assets/img/Paypal_Donate.png" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12">
                                        <p class="forms-notes">
                                            Note: The Hope For Humanity Foundation is a US tax-exempt 501(c)(3) non-profit organization. Your gift is tax-deductible as allowed by law.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- donation form popup -->

        <script src="assets/js/jquery.min.js"></script>
        <!-- Switcher Style Js -->
        <script src="assets/js/style-switcher/assets/js/style.switcher.js"></script>
        <script src="assets/js/jquery.cookie.js"></script>
        <!-- Switcher Style End Js -->
        <script src="assets/js/bootstrap.min.js"></script>
        <script src="assets/js/jquery.easing.min.js"></script>
        <!--Main Slider Js-->
        <script src="assets/revolution-slider/js/jquery.themepunch.plugins.min.js"></script>
        <script src="assets/revolution-slider/js/jquery.themepunch.revolution.js"></script>
        <!--Main Slider End Js-->
        <script src="assets/js/jquery.flexslider.js"></script>
        <script src="assets/js/site.js"></script>
        <!--Custom Js validation & stuff-->
        <script src="assets/js/custom.js"></script>
        <script>
            // functions autocomplete
            var people = ['<a href="CauseDetails.aspx?Request=101200">Shelter</a><br/>',
                '<a href="CauseDetails.aspx?Request=101201">Educate Girls</a><br/>',
                '<a href="CauseDetails.aspx?Request=101202">Grow Food</a><br/>',
                '<a href="CauseDetails.aspx?Request=101203">Feed a child</a><br/>',
                '<a href="CauseDetails.aspx?Request=101204">Build Schools</a><br/>',
                '<a href="CauseDetails.aspx?Request=101205">Health Care</a><br/>',
                '<a href="Volunteer.aspx">Volunteer</a><br/>',
                '<a href="Ourstory.aspx">Our Story</a><br/>',
                '<a href="Ourmission.aspx">Our Story</a><br/>',
                '<a href="Ourstory.aspx">Our Mission</a><br/>',
                '<a href="Events.aspx">Events</a><br/>',
                '<a href="Blog.aspx">Blog</a><br/>'];

            function matchPeople(input) {
                var reg = new RegExp(input.split('').join('\\w*\\s*\\w*').replace(/\W/, ""), 'i');
                return people.filter(function (person) {
                    if (person.match(reg)) {
                        return person;
                    }
                });
            }

            function changeInput(val) {
                var test = '';                
                var autoCompleteResult = matchPeople(val);
                if (val != '') {
                    for (i = 0; i < autoCompleteResult.length; i++) {
                        test += autoCompleteResult[i];                        
                    }
                    document.getElementById("result").innerHTML = test;
                }
                else
                    document.getElementById("result").innerHTML = '';
            }
        </script>
    </form>
</body>
</html>
