<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Events.aspx.cs" Inherits="HopeForHumanity.Events" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <script src="assets/js/gtag.js"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="keywords" content="African Children, Orphans, Donate, Donation, Charity, Shelter, Rehabilitation" />
    <!--Search engine optimization-->
    <meta name="description" content="Hope for humanity is a foundation that provides help to people in need, feeding and nurturing african children, orphans. Charity website. Donate to african children. Free slaves Libya" />
    <meta name="robots" content="index,follow" />
    <meta name="DC.title" content="Hope For Humanity Charity Website" />
    <title>Events - Hope For Humanity</title>
    <link rel="shortcut icon" type="image/x-icon" href="favico.ico" />
    <!-- google fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lato:400,300italic,300,700%7CPlayfair+Display:400,700italic%7CRoboto:300%7CMontserrat:400,700%7COpen+Sans:400,300%7CLibre+Baskerville:400,400italic' rel='stylesheet' type='text/css' />
    <!-- Bootstrap -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="assets/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="assets/revolution-slider/css/settings.css" rel="stylesheet" />
    <link href="assets/css/global.css" rel="stylesheet" />
    <link href="assets/css/style.css" rel="stylesheet" />
    <link href="assets/css/responsive.css" rel="stylesheet" />
    <link href="assets/css/skin.css" rel="stylesheet" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
    <form id="form1" runat="server">
        <div id="wrapper">
            <!--Header Section Start Here -->
            <header id="header">
                <div class="container">
                    <div class="row primary-header">
                        <a href="Default.aspx" class="col-xs-12 col-sm-2 brand" title="Welcome to Hope For Humanity">
                            <img src="assets/img/logo.png" alt="Hope For Humanity" /></a>
                        <div class="social-links col-xs-12 col-sm-10">
                            <a href="Volunteer.aspx" class="btn btn-default btn-volunteer">Become volunteer</a>
                            <div runat="server" id="divLinks">
                                <!--Loaded from codebehind-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <!--MainMenu -->
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div id="divMainMenu" runat="server">
                            <!-- This part is autogenerated from backend code FillItems() -->
                        </div>
                        <!-- /.navbar-collapse -->
                        <!--MainMenu-->
                    </div>
                    <!-- /.container-fluid -->
                </div>

            </header>
            <!-- Header Section End Here -->

            <!-- site content -->
            <div id="main">
                <!--Breadcrumb Section Start Here-->
                <div class="breadcrumb-section">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <h1>Event</h1>
                                <ul class="breadcrumb">
                                    <li>
                                        <a href="Default.aspx">Home</a>
                                    </li>
                                    <li class="active">Event
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!--Breadcrumb Section End Here-->

                <div class="cause-page content-wrapper" id="page-info">
                    <div class="container">
                        <!-- our causes detail-->
                        <div class="anim-section">
                            <div class="row">
                                <div class="col-xs-12 col-sm-9 left-block event_page">
                                    <div class="event_detail">
                                        <figure>
                                            <img src="assets/img/img_container-runner.jpg" alt="img_container" />
                                        </figure>
                                        <div class="event_date">
                                            <strong>05</strong> <span>August</span>
                                        </div>
                                    </div>
                                    <div class="event_heading clearfix">
                                        <h2><a href="#">Half Marathon event for fundraising</a></h2>
                                        <div class="event_time clearfix">
                                            <div class="venue_block">
                                                <div class="location-svg">
                                                    <img src="assets/svg/location.svg" alt="" class="svg" />
                                                </div>
                                                <span>venue :</span>
                                                <strong>Kigali, Rwanda</strong>
                                            </div>
                                            <div class="date_block">
                                                <div class="date-svg">
                                                    <img src="assets/svg/calendar.svg" alt="" class="svg" />
                                                </div>
                                                <span>date :</span>
                                                <strong>05-08-2017</strong>
                                            </div>
                                            <div class="time_block">
                                                <div class="time-svg">
                                                    <img src="assets/svg/timer.svg" alt="" class="svg" />
                                                </div>
                                                <span>Time :</span>
                                                <strong>10 PM</strong>
                                            </div>
                                        </div>
                                        <div class="event_descriptions">
                                            <p>
                                                Hundreds of youth participated in a Half Marathon held Saturday, Aug 05, 10:00 p.m. - at Glory High School, KG 690 Street, Kigali, Rwanda. The Half Marathon culminated a year-long series of fundraising efforts held throughout the year.
                                            </p>
                                            <a href="EventDetails.aspx?Request=101300" class="btn btn-default">Read More</a>
                                        </div>
                                    </div>
                                    <div class="event_info">
                                        <div class="event_detail  ">
                                            <figure>
                                                <img src="assets/img/img_container-cyclist.jpg" alt="img_container" />
                                            </figure>
                                            <div class="event_date">
                                                <strong>09</strong> <span>Sept</span>
                                            </div>
                                        </div>
                                        <div class="event_heading clearfix">
                                            <h2><a href="#">Cycle Racing Event</a></h2>
                                            <div class="event_time clearfix">
                                                <div class="venue_block">
                                                    <div class="location-svg">
                                                        <img src="assets/svg/location.svg" alt="" class="svg" />
                                                    </div>
                                                    <span>venue :</span>
                                                    <strong>Kampala, Uganda</strong>
                                                </div>
                                                <div class="date_block">
                                                    <div class="date-svg">
                                                        <img src="assets/svg/calendar.svg" alt="" class="svg" />
                                                    </div>
                                                    <span>date :</span>
                                                    <strong>09-09-2017</strong>
                                                </div>
                                                <div class="time_block">
                                                    <div class="time-svg">
                                                        <img src="assets/svg/timer.svg" alt="" class="svg" />
                                                    </div>
                                                    <span>Time :</span>
                                                    <strong>10 AM</strong>
                                                </div>
                                            </div>
                                            <div class="event_descriptions">
                                                <p>
                                                    This event was held in Uganda's capital Kampala on Saturday, 09 Sep from 10 AM in the morning. Hundreds of youth turned up to grace the occassion which included events such as road bicycle racing, time trialling, cyclo-cross and mountain bike racing.
                                                </p>
                                                <a href="EventDetails.aspx?Request=101301" class="btn btn-default">Read More</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="event_video">
                                        <div class="video  ">
                                            <iframe width="560" height="315" src="https://www.youtube.com/embed/QBY7DKE0vI4?autoplay=0" allowfullscreen></iframe>
                                        </div>
                                        <div class="event_heading clearfix">
                                            <h2><a href="#">Volunteering for a better life for children in Africa</a></h2>
                                            <div class="event_time clearfix">
                                                <div class="venue_block">
                                                    <div class="location-svg">
                                                        <img src="assets/svg/location.svg" alt="" class="svg" />
                                                    </div>
                                                    <span>venue :</span>
                                                    <strong>Nairobi, Kenya</strong>
                                                </div>
                                                <div class="date_block">
                                                    <div class="date-svg">
                                                        <img src="assets/svg/calendar.svg" alt="" class="svg" />
                                                    </div>
                                                    <span>date :</span>
                                                    <strong>03-03-2018</strong>
                                                </div>
                                                <div class="time_block">
                                                    <div class="time-svg">
                                                        <img src="assets/svg/timer.svg" alt="" class="svg" />
                                                    </div>
                                                    <span>Time :</span>
                                                    <strong>10 AM</strong>
                                                </div>
                                            </div>
                                            <div class="event_descriptions">
                                                <p>
                                                    Many underprivileged children in Africa have limited opportunity for sporting activities, necessary for physical development and important in learning social and life skills. You can put to use your sporting skills and passion to change these kids’ lives and ensure a better future for them.
                                                </p>
                                                <a href="EventDetails.aspx?Request=101302" class="btn btn-default">Read More</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <div class="col-xs-12 col-sm-3 left-block ">
                                    <!--Most Popular Events-->
                                    <aside class="media">
                                        <h3 class="space-top">Most Popular Events</h3>
                                        <ul>
                                            <li>
                                                <a href="EventDetails.aspx?Request=101300" class="pull-left">
                                                    <figure>
                                                        <img src="assets/img/aside-img-01.jpg" alt="" />
                                                    </figure>
                                                </a>
                                                <div class="media-body">
                                                    <p>
                                                        <a href="EventDetails.aspx?Request=101300">Half Marathon event for fundraising
                                                        </a>
                                                    </p>
                                                    <span>05, August 2017 </span>
                                                </div>
                                            </li>
                                            <li>
                                                <a href="EventDetails.aspx?Request=101301" class="pull-left">
                                                    <figure>
                                                        <img src="assets/img/aside-img-02.jpg" alt="" />
                                                    </figure>
                                                </a>
                                                <div class="media-body">
                                                    <p>
                                                        <a href="EventDetails.aspx?Request=101301">Cycle Racing Event
                                                        </a>
                                                    </p>
                                                    <span>09, September 2017 </span>
                                                </div>
                                            </li>
                                            <li>
                                                <a href="EventDetails.aspx?Request=101302" class="pull-left">
                                                    <figure>
                                                        <img src="assets/img/aside-img-03.jpg" alt="" />
                                                    </figure>
                                                </a>
                                                <div class="media-body">
                                                    <p>
                                                        <a href="EventDetails.aspx?Request=101302">Volunteer for a better life
                                                        </a>
                                                    </p>
                                                    <span>03, March 2018 </span>
                                                </div>
                                            </li>
                                        </ul>
                                    </aside>
                                    <!--Most Popular Events Ends-->

                                    <!-- Archives   -->
                                    <aside class="media">
                                        <h3>Archives</h3>
                                        <ul class="archives">
                                            <li>
                                                <a href="Events.aspx">August 2017 <span class="pull-right">(1)</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="Events.aspx">September 2017 <span class="pull-right">(1)</span>
                                                </a>
                                            </li>
                                            <li><a href="Events.aspx">March 2018 <span class="pull-right">(1)</span>
                                            </a>
                                            </li>
                                            <li><a href="Events.aspx">August 2017 <span class="pull-right">(1)</span>
                                            </a>
                                            </li>
                                            <li>
                                                <a href="Events.aspx">September 2017 <span class="pull-right">(1)</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </aside>
                                    <!-- Archives  End -->

                                </div>
                            </div>
                        </div>
                        <!-- our causes detail-->
                    </div>
                </div>
            </div>
            <!-- site content ends -->

            <!--Footer Section Start Here -->
            <footer id="footer">
                <div class="container" runat="server" id="divFooter">
                    <!--Generated From codebehind-->
                </div>
                <div class="copyright">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <span>&copy; Copyright
                                    <script>document.write(new Date().getFullYear())</script>
                                    , All Rights Reserved by Hope For Humanity Foundation.
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <!--Footer Section End Here -->
        </div>

        <!-- donation form popup -->
        <div class="modal donate-form">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                        <header class="page-header">
                            <h2>You are donating to. <strong>Hope For Humanity</strong></h2>
                        </header>
                    </div>
                    <div class="modal-body">
                        <div role="form">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label>How much would you like to donate ?<br /> (NB: We accept bitcoin.)</label>
                                        <div class="choose-pricing">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default active" onclick="mySetDonation('25')">
                                                    $25
                                                </button>
                                                <button type="button" class="btn btn-default" onclick="mySetDonation('50')">
                                                    $50
                                                </button>
                                                <button type="button" class="btn btn-default" onclick="mySetDonation('100')">
                                                    $100
                                                </button>
                                                <input type="text" placeholder="Custom" class="inpt-first form-control" runat="server" id="iAmount" />
                                                <asp:HiddenField runat="server" ID="hfAmount" Value="25" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row display">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <div class="dropdown">
                                            <asp:DropDownList ID="ddlType" runat="server" class="btn btn-width dropdown-toggle">
                                                <asp:ListItem Text="Donation Type" Value="Type"></asp:ListItem>
                                                <asp:ListItem Text="Educate A Child" Value="Educate"></asp:ListItem>
                                                <asp:ListItem Text="Feed A Child" Value="Feed"></asp:ListItem>
                                                <asp:ListItem Text="Grow Food" Value="Grow"></asp:ListItem>
                                                <asp:ListItem Text="Build Schools" Value="School"></asp:ListItem>
                                                <asp:ListItem Text="Health Care" Value="Health"></asp:ListItem>
                                            </asp:DropDownList>
                                            <label id="ddlType-error" style="color: red; display: none;">*</label>
                                        </div>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <div class="dropdown">
                                            <asp:DropDownList ID="ddlFreq" runat="server" class="btn btn-width dropdown-toggle">
                                                <asp:ListItem Text="One Time Donation" Value="Once" Selected></asp:ListItem>
                                                <asp:ListItem Text="Every Month (Recurring)" Value="Monthly"></asp:ListItem>
                                            </asp:DropDownList>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="name">First Name<span>*</span></label>
                                        <input type="text" class="form-control" id="fname" runat="server" />
                                        <label id="fname-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="last-name">Last Name<span>*</span></label>
                                        <input type="text" class="form-control" id="lname" runat="server" />
                                        <label id="lname-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="name">Email<span>*</span></label>
                                        <input type="text" class="form-control" id="email" runat="server" />
                                        <label id="email-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="phone">Phone<span>*</span></label>
                                        <input type="text" class="form-control" id="phone" runat="server" />
                                        <label id="phone-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="message">Address<span>*</span></label>
                                        <textarea class="form-control" id="Address" runat="server"></textarea>
                                        <label id="Address-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="add-note">Additional Note</label>
                                        <textarea class="form-control" id="message" runat="server"></textarea>
                                        <label id="message-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12">
                                        <asp:Button runat="server" ID="btnDonateBitcoin" Text="DONATE WITH BITCOIN" class="btn btn-default pull-left" OnClientClick="return validateForm()" OnClick="btnDonateBitcoin_Click" />
                                        <asp:Button runat="server" ID="btnDonate" Text="DONATE" class="btn btn-default pull-right" OnClientClick="return validateForm()" OnClick="btnDonate_Click" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12">
                                        <p class="forms-notes">
                                            Note: The Hope For Humanity Foundation is a US tax-exempt 501(c)(3) non-profit organization. Your gift is tax-deductible as allowed by law.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- donation form popup -->

        <script src="assets/js/jquery.min.js"></script>
        <!-- Switcher Style Js -->
        <script src="assets/js/style-switcher/assets/js/style.switcher.js"></script>
        <script src="assets/js/jquery.cookie.js"></script>
        <!-- Bootstrap Js-->
        <script src="assets/js/bootstrap.min.js"></script>
        <script src="assets/js/jquery.easing.min.js"></script>
        <!--Main Slider Js-->
        <script src="assets/revolution-slider/js/jquery.themepunch.plugins.min.js"></script>
        <script src="assets/revolution-slider/js/jquery.themepunch.revolution.js"></script>
        <!--Main Slider Js End -->
        <script src="assets/js/jquery.flexslider.js"></script>
        <script src="assets/js/site.js"></script>
        <!--Custom Js validation & stuff-->
        <script src="assets/js/custom.js"></script>
        <script>
            // functions autocomplete
            var people = ['<a href="CauseDetails.aspx?Request=101200">Shelter</a><br/>',
                '<a href="CauseDetails.aspx?Request=101201">Educate Girls</a><br/>',
                '<a href="CauseDetails.aspx?Request=101202">Grow Food</a><br/>',
                '<a href="CauseDetails.aspx?Request=101203">Feed a child</a><br/>',
                '<a href="CauseDetails.aspx?Request=101204">Build Schools</a><br/>',
                '<a href="CauseDetails.aspx?Request=101205">Health Care</a><br/>',
                '<a href="Volunteer.aspx">Volunteer</a><br/>',
                '<a href="Ourstory.aspx">Our Story</a><br/>',
                '<a href="Ourmission.aspx">Our Story</a><br/>',
                '<a href="Ourstory.aspx">Our Mission</a><br/>',
                '<a href="Events.aspx">Events</a><br/>',
                '<a href="Blog.aspx">Blog</a><br/>'];

            function matchPeople(input) {
                var reg = new RegExp(input.split('').join('\\w*\\s*\\w*').replace(/\W/, ""), 'i');
                return people.filter(function (person) {
                    if (person.match(reg)) {
                        return person;
                    }
                });
            }

            function changeInput(val) {
                var test = '';
                var autoCompleteResult = matchPeople(val);
                if (val != '') {
                    for (i = 0; i < autoCompleteResult.length; i++) {
                        test += autoCompleteResult[i];
                    }
                    document.getElementById("result").innerHTML = test;
                }
                else
                    document.getElementById("result").innerHTML = '';
            }
        </script>
    </form>
</body>
</html>
