<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Faq.aspx.cs" Inherits="HopeForHumanity.Faq" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <script src="assets/js/gtag.js"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="keywords" content="African Children, Orphans, Donate, Donation, Charity, Shelter, Rehabilitation" />
    <!--Search engine optimization-->
    <meta name="description" content="Hope for humanity is a foundation that provides help to people in need, feeding and nurturing african children, orphans. Charity website. Donate to african children. Free slaves Libya" />
    <meta name="robots" content="index,follow" />
    <meta name="DC.title" content="Hope For Humanity Charity Website" />
    <title>FAQ - Hope For Humanity</title>
    <link rel="shortcut icon" type="image/x-icon" href="favico.ico" />
    <!-- google fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lato:400,300italic,300,700%7CPlayfair+Display:400,700italic%7CRoboto:300%7CMontserrat:400,700%7COpen+Sans:400,300%7CLibre+Baskerville:400,400italic' rel='stylesheet' type='text/css' />
    <!-- Bootstrap -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="assets/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="assets/revolution-slider/css/settings.css" rel="stylesheet" />
    <link href="assets/css/global.css" rel="stylesheet" />
    <link href="assets/css/style.css" rel="stylesheet" />
    <link href="assets/css/responsive.css" rel="stylesheet" />
    <link href="assets/css/skin.css" rel="stylesheet" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
    <form id="form1" runat="server">
        <div id="wrapper">
            <!--Header Section Start Here -->
            <header id="header">
                <div class="container">
                    <div class="row primary-header">
                        <a href="Default.aspx" class="col-xs-12 col-sm-2 brand" title="Welcome to Hope For Humanity">
                            <img src="assets/img/logo.png" alt="Hope For Humanity" /></a>
                        <div class="social-links col-xs-12 col-sm-10">
                            <a href="Volunteer.aspx" class="btn btn-default btn-volunteer">Become volunteer</a>
                            <div runat="server" id="divLinks">
                                <!--Loaded from codebehind-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <!--MainMenu -->
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div id="divMainMenu" runat="server">
                            <!-- This part is autogenerated from backend code FillItems() -->
                        </div>
                        <!-- /.navbar-collapse -->
                        <!--MainMenu-->
                    </div>
                    <!-- /.container-fluid -->
                </div>

            </header>
            <!-- Header Section End Here -->

            <!-- site content -->
            <div id="main">
                <!--Breadcrumb Section Start Here-->
                <div class="breadcrumb-section">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <h1>Frequently Asked Questions</h1>
                                <ul class="breadcrumb">
                                    <li>
                                        <a href="Default.aspx">Home</a>
                                    </li>
                                    <li class="active">Faq's
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!--Breadcrumb Section End Here-->

                <div class="content-wrapper" id="page-info">
                    <div class="container">

                        <div class="row">
                            <div class="col-xs-12">
                                <header class="faq-header section-header">
                                    <h2>Check out our <strong>FAQ below.</strong></h2>
                                </header>
                                <!-- Collape Section Start Here -->

                                <div class="row faq">
                                    <div class="cols-xs-12 col-sm-6 anim-section">
                                        <h3>General Questions</h3>
                                        <div class="panel-group" id="accordion">
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title">
                                                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-1">Is Hope for Humanity A Recognized Organization ? <i class="fa fa-plus collape-plus"></i></a>
                                                    </h4>
                                                </div>
                                                <div id="collapse-1" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            Hope for Humanity is a recognized fund raising non-government organization that is specially working for the welfare of African children.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-2">How Can I View Your Annual Report To Know How You Use Our Money? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-2" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            Everyone can access the annual report from our website or can have a printed copy of our financial report from the nearest office.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-3">Does the Government Provide Any Support? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-3" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            Hope for Humanity is a non-government organization. We do not get any funds directly from the government, except exemption on various taxes. This minimizes our expenses and other costs.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse-4">How Does Hope for Humanity Cover Its Own Expenses? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-4" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            Our expenses include traveling, managing resources, monitoring activities and advertising which is solely covered by all our donors and financial partners. For our office management such as information systems, furniture and other requirements, we get support from our partners for free or at a discounted rate.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-5">Why Does Hope for Humanity Not Provide Information About Children? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-5" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            We use donors’ funds in all our resources and programs to carry out children’s holistic development and other welfares. Hence, there is no use of sharing confidential information of the children. To know more about how we use your funds, you can become our partner and explore how our team works. 													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-6">Does Hope for Humanity Provide Information About Where My Donation Is Used? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-6" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            There are thousands of people, who make contributions in our projects. Therefore, it is not easy for us to prepare a report regarding a particular individual that comprises how his donation was used. But, you can check the financial report on our website.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-7">How Does Your Team Raise Funds For Resources? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-7" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            We have several events that we organise from time to time to raise awarenes and funds. Also we have partnered with major organizations & institutions as well as individuals that provide us all the resources at a reasonable discount.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-8">What Method Does Hope for Humanity Use To Choose Projects For Its Support? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-8" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            Our team comprises of experts from different backgrounds, including economists, marketing strategists, health care, business, Journalist, financial management and others. They first scrutinize every aspect of the project and after finding it suitable, they start working on it.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="cols-xs-12 col-sm-6 anim-section">
                                        <h3>General Questions</h3>
                                        <div class="panel-group" id="accordion-right">
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion-right" href="#collapse-9">Do Hope for Humanity Employees earn a Salary? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-9" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            Every full-time employee gets a salary here. Our team believes that this is the best way to bring talented professionals onboard. Here, all the employees are paid modest salaries as compared to other organizations.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion-right" href="#collapse-10">Will My Little Contribution Be Helpful To You? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-10" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            Although the problem is huge, everyone’s little contribution adds up to become a huge amount that can be invested in carrying out project tasks and campaigns in support of children's welfare smoothly.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion-right" href="#collapse-11">How Does Hope for Humanity Work To Ensure Childrens' Rights? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-11" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            We work with different communities and other NGOs to make children aware of their basic rights and help them access education and imperative health care needs.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion-right" href="#collapse-12">What Are Modes Of Making Donation? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-12" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            In order to make it convenient for everyone who wants to give a donation, there are different online payment modes like credit and debit card systems. Moreover, the user can also make a donation through Bitcoins.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion-right" href="#collapse-13">How Can I Make a Donation?  <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-13" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            You can make your donation to us either by becoming a partner or by going to our home page where you will see the different “Donate Now” options for our various programs. Just choose anyone and make a donation.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion-right" href="#collapse-14">Is Your Transaction Architecture Secure? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-14" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            Our online transaction system is completely secure and mastercard/visa compliant; rest assured that no one can easily breach or hack information regarding payments by credit or debit cards.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion-right" href="#collapse-15">How Do You Help Improve Medical Care? <i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-15" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            We are working with various NGOs and healthcare organizations that help us provide medical facilities. We also get imperative medicines to curb the existing shortage in the market.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion-right" href="#collapse-16">How Can Sponsorship Help My Business?<i class="fa fa-plus collape-plus"></i></a></h4>
                                                </div>
                                                <div id="collapse-16" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <p>
                                                            We are a growing organization. Our team organizes various special and enjoyable events that grab the attention of millions and this will automatically make your brand visible.													
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Collape Section End Here -->
                            </div>
                        </div>
                    </div>

                    <!-- ask-us -->
                    <section class="save-lives ask-us text-center">
                        <div class="container">
                            <div class="row">
                                <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                                    <header class="page-header">
                                        <h2>You still have questions? <strong>Ask us</strong></h2>
                                        <p>
                                            Is there any query left? You can directly share with us and clear away all your confusions.									
                                        </p>
                                    </header>
                                    <a class="btn btn-default" href="Contactus.aspx">ask questions</a>

                                </div>
                            </div>
                        </div>
                    </section>
                    <!-- ask-us end  -->
                </div>

            </div>
            <!-- site content ends -->

            <!--Footer Section Start Here -->
            <footer id="footer">
                <div class="container" runat="server" id="divFooter">
                    <!--Generated From codebehind-->
                </div>
                <div class="copyright">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <span>&copy; Copyright
                                    <script>document.write(new Date().getFullYear())</script>
                                    , All Rights Reserved by Hope For Humanity Foundation.
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <!--Footer Section End Here -->

        </div>
        <script src="assets/js/jquery.min.js"></script>
        <!-- Switcher Style Js -->
        <script src="assets/js/style-switcher/assets/js/style.switcher.js"></script>
        <script src="assets/js/jquery.cookie.js"></script>
        <!-- Bootstrap Js-->
        <script src="assets/js/bootstrap.min.js"></script>
        <script src="assets/js/jquery.easing.min.js"></script>
        <!--Main Slider Js-->
        <script src="assets/revolution-slider/js/jquery.themepunch.plugins.min.js"></script>
        <script src="assets/revolution-slider/js/jquery.themepunch.revolution.js"></script>
        <!--Main Slider Js End -->
        <script src="assets/js/jquery.flexslider.js"></script>
        <script src="assets/js/site.js"></script>
        <!--Custom Js validation & stuff-->
        <script src="assets/js/custom.js"></script>
        <script>
            // functions autocomplete
            var people = ['<a href="CauseDetails.aspx?Request=101200">Shelter</a><br/>',
                '<a href="CauseDetails.aspx?Request=101201">Educate Girls</a><br/>',
                '<a href="CauseDetails.aspx?Request=101202">Grow Food</a><br/>',
                '<a href="CauseDetails.aspx?Request=101203">Feed a child</a><br/>',
                '<a href="CauseDetails.aspx?Request=101204">Build Schools</a><br/>',
                '<a href="CauseDetails.aspx?Request=101205">Health Care</a><br/>',
                '<a href="Volunteer.aspx">Volunteer</a><br/>',
                '<a href="Ourstory.aspx">Our Story</a><br/>',
                '<a href="Ourmission.aspx">Our Story</a><br/>',
                '<a href="Ourstory.aspx">Our Mission</a><br/>',
                '<a href="Events.aspx">Events</a><br/>',
                '<a href="Blog.aspx">Blog</a><br/>'];

            function matchPeople(input) {
                var reg = new RegExp(input.split('').join('\\w*\\s*\\w*').replace(/\W/, ""), 'i');
                return people.filter(function (person) {
                    if (person.match(reg)) {
                        return person;
                    }
                });
            }

            function changeInput(val) {
                var test = '';
                var autoCompleteResult = matchPeople(val);
                if (val != '') {
                    for (i = 0; i < autoCompleteResult.length; i++) {
                        test += autoCompleteResult[i];
                    }
                    document.getElementById("result").innerHTML = test;
                }
                else
                    document.getElementById("result").innerHTML = '';
            }
        </script>
    </form>
</body>
</html>
