<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Ourstory.aspx.cs" Inherits="HopeForHumanity.Ourstory" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <script src="assets/js/gtag.js"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="keywords" content="African Children, Orphans, Donate, Donation, Charity, Shelter, Rehabilitation" />
    <!--Search engine optimization-->
    <meta name="description" content="Hope for humanity is a foundation that provides help to people in need, feeding and nurturing african children, orphans. Charity website. Donate to african children. Free slaves Libya" />
    <meta name="robots" content="index,follow" />
    <meta name="DC.title" content="Hope For Humanity Charity Website" />
    <title>Our Story - Hope For Humanity</title>
    <link rel="shortcut icon" type="image/x-icon" href="favico.ico" />
    <!-- google fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lato:400,300italic,300,700%7CPlayfair+Display:400,700italic%7CRoboto:300%7CMontserrat:400,700%7COpen+Sans:400,300%7CLibre+Baskerville:400,400italic' rel='stylesheet' type='text/css' />
    <!-- Bootstrap -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="assets/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="assets/revolution-slider/css/settings.css" rel="stylesheet" />
    <link href="assets/css/global.css" rel="stylesheet" />
    <link href="assets/css/style.css" rel="stylesheet" />
    <link href="assets/css/responsive.css" rel="stylesheet" />
    <link href="assets/css/skin.css" rel="stylesheet" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
    <form id="form1" runat="server">
        <div id="wrapper">
            <!--Header Section Start Here -->
            <header id="header">
                <div class="container">
                    <div class="row primary-header">
                        <a href="Default.aspx" class="col-xs-12 col-sm-2 brand" title="Welcome to Hope For Humanity">
                            <img src="assets/img/logo.png" alt="Hope For Humanity" /></a>
                        <div class="social-links col-xs-12 col-sm-10">
                            <a href="Volunteer.aspx" class="btn btn-default btn-volunteer">Become volunteer</a>
                            <div runat="server" id="divLinks">
                                <!--Loaded from codebehind-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <!--MainMenu -->
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div id="divMainMenu" runat="server">
                            <!-- This part is autogenerated from backend code FillItems() -->
                        </div>
                        <!-- /.navbar-collapse -->
                        <!--MainMenu-->
                    </div>
                    <!-- /.container-fluid -->
                </div>

            </header>
            <!-- Header Section End Here -->
            <!-- site content -->
            <div id="main">
                <!-- Breadcrumb Section Start Here -->
                <div class="breadcrumb-section">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <h1>Our Story</h1>
                                <ul class="breadcrumb">
                                    <li>
                                        <a href="Default.aspx">Home</a>
                                    </li>
                                    <li class="active">Our Story
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Breadcrumb Section End Here -->

                <div class="content-wrapper" id="page-info">
                    <div class="container">
                        <!-- Our Story Section Start Here -->
                        <section class="our-story row">
                            <div class="col-xs-12">
                                <header class="story-heading section-header">
                                    <h2>Who we are? <strong>Read our Story</strong></h2>
                                </header>
                                <div class="row">
                                    <div class="col-xs-12 col-sm-5">
                                        <section class="slider-wrap flex-slide flexslider">
                                            <ul class="slides">
                                                <li>
                                                    <img src="assets/img/img-slide-01.jpg" alt="" />
                                                </li>
                                                <li>
                                                    <img src="assets/img/img-slide-02.jpg" alt="" />
                                                </li>
                                            </ul>
                                        </section>
                                    </div>
                                    <div class="col-xs-12 col-sm-7">
                                        <strong class="article-sammury">Hope for humanity is an extensive platform, where anyone from any part of the world can donate and contribute to the little part of the entire fortune to enhance living standards and education as well as fulfill all other basic needs of deprived African children.											
                                        </strong>
                                        <p>
                                            We do not raise funds for an unworthy cause. Indeed, we use all the funds that come through Hope for humanity in the best interest of african children in terms of holistic development of children of all age groups. Our team is relentlessly working day and night to ensure that there will be no hassle to our fund donor.									
                                        </p>
                                        <p>
                                            We work for children's welfare, those who are daily exploited and living in conditions deprived of a healthy environment, proper education, food, clothing and medical care. 									
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </section>
                        <!-- Our Story Section Start Here -->

                        <!-- What We Do Section Start Here-->
                        <section class="our-works row anim-section">
                            <div class="col-xs-12">
                                <header class="work-block-heading section-header">
                                    <h2>What we do? <strong>See Our Works</strong></h2>
                                </header>
                                <div class="row">
                                    <div class="col-xs-12 col-sm-6 col-md-3">
                                        <div class="thumbnail zoom">
                                            <h3>Donation Causes</h3>
                                            <a href="Causes.aspx" class="img-thumb">
                                                <figure>
                                                    <img src="assets/img/img-slide-01.jpg" alt="" />
                                                </figure>
                                            </a>
                                            <p>
                                                We encourage you to help us raise funds for charity causes that greatly improve the quality of living of African children, who are living in poor and degraded conditions.										
                                            </p>
                                            <p>
                                                <a href="Causes.aspx" class="btn btn-default btn-sm" role="button">READ MORE</a>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-6 col-md-3">
                                        <div class="thumbnail zoom">
                                            <h3>Creative Events</h3>
                                            <a href="Events.aspx" class="img-thumb">
                                                <figure>
                                                    <img src="assets/img/img-slide-02.jpg" alt="" />
                                                </figure>
                                            </a>
                                            <p>
                                                Hope for humanity organizes different events to raise money for children’s welfare. We have generated around 48% of the funds through various different events. 										
                                            </p>
                                            <p>
                                                <a href="Events.aspx" class="btn btn-default btn-sm" role="button">READ MORE</a>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-6 col-md-3">
                                        <div class="thumbnail zoom">
                                            <h3>Sponsorships</h3>
                                            <a href="CauseDetaials.aspx?Request=101206" class="img-thumb">
                                                <figure>
                                                    <img src="assets/img/img-slide-05.jpg" alt="" />
                                                </figure>
                                            </a>
                                            <p>
                                                Our sponsorships program has not only helped us achieve our mission, but also seen over 100,000 children living in slums and rural Africa improve their living conditions and education.										
                                            </p>
                                            <p>
                                                <a href="CauseDetails.aspx?Request=101206" class="btn btn-default btn-sm" role="button">READ MORE</a>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-6 col-md-3">
                                        <div class="thumbnail">
                                            <h3>Volunteer</h3>
                                            <a href="Volunteer.aspx" class="img-thumb">
                                                <figure>
                                                    <img src="assets/img/volunteer.jpg" alt="" />
                                                </figure>
                                            </a>
                                            <p>
                                                Join us? Be a part of our family of volunteers, whose efforts have propelled us to reach our envisioned goals without a hussle. We need those extra hands today. 										
                                            </p>
                                            <p>
                                                <a href="Volunteer.aspx" class="btn btn-default btn-sm" role="button">READ MORE</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                        <!-- What We Do Section Start Here-->
                    </div>

                    <!-- Helping Section Start here-->
                    <section class="helping-child parallax">
                        <div class="container">
                            <div class="row">
                                <div class="col-xs-12 col-sm-7 col-md-5">
                                    <h2 class="h1">Helping a child in <strong class="border-none">Africa</strong></h2>
                                    <p>You are Just A Few Clicks Away From Bringing a Smile To Children in Africa. </p>
                                    <a data-toggle="modal" href="~/Error404.aspx" data-target=".donate-form" class="btn btn-theme">Donate now</a>
                                </div>
                            </div>
                        </div>
                    </section>
                    <!-- Helping Section Start here-->

                    <!-- Our Team Section Start Here -->
                    <div class="container">
                        <div class="our-team text-center row">
                            <div class="col-xs-12">
                                <header class="team-info section-header">
                                    <h2>We are Real. <strong>Meet the Team</strong></h2>
                                </header>
                                <div class="row">
                                    <div class="col-xs-12 col-sm-3 anim-section">
                                        <div class="thumbnail">
                                            <figure>
                                                <img src="assets/img/team-member1.jpg" alt="" />
                                            </figure>
                                            <div class="caption">
                                                <h3>Ernest Mukiri</h3>
                                                <ul class="social-icons">
                                                    <li>
                                                        <a href="https://www.facebook.com/profile.php?id=100023681619977" target="_blank"><i class="fa fa-facebook"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://twitter.com/jameskerr5244" target="_blank"><i class="fa fa-twitter"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://plus.google.com/u/0/111200409794406676775" target="_blank"><i class="fa fa-google-plus"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://www.instagram.com/jameskerr5244/" target="_blank"><i class="fa fa-instagram"></i></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-3 anim-section">
                                        <div class="thumbnail">
                                            <figure>
                                                <img src="assets/img/team-member2.jpg" alt="" />
                                            </figure>
                                            <div class="caption">
                                                <h3>Hilda Stone</h3>
                                                <ul class="social-icons">
                                                    <li>
                                                        <a href="https://www.facebook.com/hilda.stone.79069" target="_blank"><i class="fa fa-facebook"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://twitter.com/hildastone86" target="_blank"><i class="fa fa-twitter"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://plus.google.com/u/1/104619785355400664321" target="_blank"><i class="fa fa-google-plus"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://www.instagram.com/hildastone86/" target="_blank"><i class="fa fa-instagram"></i></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-3 anim-section">
                                        <div class="thumbnail">
                                            <figure>
                                                <img src="assets/img/team-member3.jpg" alt="" />
                                            </figure>
                                            <div class="caption">
                                                <h3>Allan Erissat</h3>
                                                <ul class="social-icons">
                                                    <li>
                                                        <a href="https://www.facebook.com/profile.php?id=100023704566525" target="_blank"><i class="fa fa-facebook"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://twitter.com/tomyoung732" target="_blank"><i class="fa fa-twitter"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://plus.google.com/u/2/105196447399796491148" target="_blank"><i class="fa fa-google-plus"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://www.instagram.com/tomyoung732/" target="_blank"><i class="fa fa-instagram"></i></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-3 anim-section">
                                        <div class="thumbnail">
                                            <figure>
                                                <img src="assets/img/team-member4.jpg" alt="" />
                                            </figure>
                                            <div class="caption">
                                                <h3>Renox Omache</h3>
                                                <ul class="social-icons">
                                                    <li>
                                                        <a href="https://www.facebook.com/ella.raynor.71" target="_blank"><i class="fa fa-facebook"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://twitter.com/ellaraynor69" target="_blank"><i class="fa fa-twitter"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://plus.google.com/u/3/110530137461092771226" target="_blank"><i class="fa fa-google-plus"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="https://www.instagram.com/ellaraynor69/" target="_blank"><i class="fa fa-instagram"></i></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Our Team Section Ends Here -->

                </div>
            </div>
            <!-- site content ends -->

            <!--Footer Section Start Here -->
            <footer id="footer">
                <div class="container" runat="server" id="divFooter">
                    <!--Generated From codebehind-->
                </div>
                <div class="copyright">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <span>&copy; Copyright
                                    <script>document.write(new Date().getFullYear())</script>
                                    , All Rights Reserved by Hope For Humanity Foundation.
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <!--Footer Section End Here -->
        </div>

        <!-- donation form popup -->
        <div class="modal donate-form">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                        <header class="page-header">
                            <h2>You are donating to. <strong>Hope For Humanity</strong></h2>
                        </header>
                    </div>
                    <div class="modal-body">
                        <div role="form">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label>How much would you like to donate ?<br /> (NB: We accept bitcoin.)</label>
                                        <div class="choose-pricing">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default active" onclick="mySetDonation('25')">
                                                    $25
                                                </button>
                                                <button type="button" class="btn btn-default" onclick="mySetDonation('50')">
                                                    $50
                                                </button>
                                                <button type="button" class="btn btn-default" onclick="mySetDonation('100')">
                                                    $100
                                                </button>
                                                <input type="text" placeholder="Custom" class="inpt-first form-control" runat="server" id="iAmount" />
                                                <asp:HiddenField runat="server" ID="hfAmount" Value="25" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row display">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <div class="dropdown">
                                            <asp:DropDownList ID="ddlType" runat="server" class="btn btn-width dropdown-toggle">
                                                <asp:ListItem Text="Donation Type" Value="Type"></asp:ListItem>
                                                <asp:ListItem Text="Educate A Child" Value="Educate"></asp:ListItem>
                                                <asp:ListItem Text="Feed A Child" Value="Feed"></asp:ListItem>
                                                <asp:ListItem Text="Grow Food" Value="Grow"></asp:ListItem>
                                                <asp:ListItem Text="Build Schools" Value="School"></asp:ListItem>
                                                <asp:ListItem Text="Health Care" Value="Health"></asp:ListItem>
                                            </asp:DropDownList>
                                            <label id="ddlType-error" style="color: red; display: none;">*</label>
                                        </div>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <div class="dropdown">
                                            <asp:DropDownList ID="ddlFreq" runat="server" class="btn btn-width dropdown-toggle">
                                                <asp:ListItem Text="One Time Donation" Value="Once" Selected></asp:ListItem>
                                                <asp:ListItem Text="Every Month (Recurring)" Value="Monthly"></asp:ListItem>
                                            </asp:DropDownList>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="name">First Name<span>*</span></label>
                                        <input type="text" class="form-control" id="fname" runat="server" />
                                        <label id="fname-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="last-name">Last Name<span>*</span></label>
                                        <input type="text" class="form-control" id="lname" runat="server" />
                                        <label id="lname-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="name">Email<span>*</span></label>
                                        <input type="text" class="form-control" id="email" runat="server" />
                                        <label id="email-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="phone">Phone<span>*</span></label>
                                        <input type="text" class="form-control" id="phone" runat="server" />
                                        <label id="phone-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="message">Address<span>*</span></label>
                                        <textarea class="form-control" id="Address" runat="server"></textarea>
                                        <label id="Address-error" style="color: red; display: none;">*</label>
                                    </div>
                                    <div class="form-group col-xs-12 col-sm-6">
                                        <label for="add-note">Additional Note</label>
                                        <textarea class="form-control" id="message" runat="server"></textarea>
                                        <label id="message-error" style="color: red; display: none;">*</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12">
                                        <asp:Button runat="server" ID="btnDonateBitcoin" Text="DONATE WITH BITCOIN" class="btn btn-default pull-left" OnClientClick="return validateForm()" OnClick="btnDonateBitcoin_Click" />
                                        <asp:Button runat="server" ID="btnDonate" Text="DONATE" class="btn btn-default pull-right" OnClientClick="return validateForm()" OnClick="btnDonate_Click" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group col-xs-12">
                                        <p class="forms-notes">
                                            Note: The Hope For Humanity Foundation is a US tax-exempt 501(c)(3) non-profit organization. Your gift is tax-deductible as allowed by law.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- donation form popup -->

        <script src="assets/js/jquery.min.js"></script>
        <!-- Switcher Style Js -->
        <script src="assets/js/style-switcher/assets/js/style.switcher.js"></script>
        <script src="assets/js/jquery.cookie.js"></script>
        <!-- Bootstrap Js-->
        <script src="assets/js/bootstrap.min.js"></script>
        <script src="assets/js/jquery.easing.min.js"></script>
        <!--Main Slider Js-->
        <script src="assets/revolution-slider/js/jquery.themepunch.plugins.min.js"></script>
        <script src="assets/revolution-slider/js/jquery.themepunch.revolution.js"></script>
        <!--Main Slider Js End -->
        <script src="assets/js/jquery.flexslider.js"></script>
        <script src="assets/js/site.js"></script>
        <!--Custom Js validation & stuff-->
        <script src="assets/js/custom.js"></script>
        <script>
            // functions autocomplete
            var people = ['<a href="CauseDetails.aspx?Request=101200">Shelter</a><br/>',
                '<a href="CauseDetails.aspx?Request=101201">Educate Girls</a><br/>',
                '<a href="CauseDetails.aspx?Request=101202">Grow Food</a><br/>',
                '<a href="CauseDetails.aspx?Request=101203">Feed a child</a><br/>',
                '<a href="CauseDetails.aspx?Request=101204">Build Schools</a><br/>',
                '<a href="CauseDetails.aspx?Request=101205">Health Care</a><br/>',
                '<a href="Volunteer.aspx">Volunteer</a><br/>',
                '<a href="Ourstory.aspx">Our Story</a><br/>',
                '<a href="Ourmission.aspx">Our Story</a><br/>',
                '<a href="Ourstory.aspx">Our Mission</a><br/>',
                '<a href="Events.aspx">Events</a><br/>',
                '<a href="Blog.aspx">Blog</a><br/>'];

            function matchPeople(input) {
                var reg = new RegExp(input.split('').join('\\w*\\s*\\w*').replace(/\W/, ""), 'i');
                return people.filter(function (person) {
                    if (person.match(reg)) {
                        return person;
                    }
                });
            }

            function changeInput(val) {
                var test = '';
                var autoCompleteResult = matchPeople(val);
                if (val != '') {
                    for (i = 0; i < autoCompleteResult.length; i++) {
                        test += autoCompleteResult[i];
                    }
                    document.getElementById("result").innerHTML = test;
                }
                else
                    document.getElementById("result").innerHTML = '';
            }
        </script>
    </form>
</body>
</html>
